# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4baa0253e44e2a41c77dad4e114a59543245c6524daacb168c0dedec4c96c2634108294dd4f42f6367e62f7fb5b9c2ac756bd9807c4b195ba2517d56695b46e

test:
  secret_key_base: 640857fbaacc9a99e0eadc21cbfa34b4c69aa04f9f7d1a8bead4a16e7cb90e219b24f5dd1af3a15db66b6118c4cd5732005c8c23bbcbd438096a94f309ef1faa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
